import logging

TCP_PORT = 4444
TCP_HOST = "0.0.0.0"

CONTROL_QUEUE_SIZE = 10

DEFAULT_SPEED_PERCENT = 80
DEFAULT_RUNTIME_S = 4.45
DEFAULT_ANGLE = 45

LOGGING_LEVEL = logging.DEBUG
LOGGING_FORMAT = "%(asctime)s %(levelname)s  %(message)s"
